### ISSUE TITLE
Ma la gente è pazza!

### ISSUE THREAD

**Issue by portapipe** [francesco-strazzullo/rest-slim-seed#1]
Ci tenevo a lasciare la mia sbigottita reazione nel vedere 0 Fork e 0 Stelle a questo progetto.
Quante volte ho dovuto impostare da zero il servizio REST con SlimFramework, e senza Middleware e SQLite (sempre rigorosamente MySQL).
Cercavo un progetto pre-impostato da inserire drag&drop ai miei numerosi progetti ma solo ora l'ho trovato! E pure in italiano! (non che sia un problema ma sai.. sempre italiani siamo)

Forkato subito (visto l'eccellente funzionamento sui miei server hostati di SQLite e htaccess) e stellato!
Ecco manca solo l'htaccess che ti invio subito!

**Comment by francesco-strazzullo** [comment]
Grande! Grazie mille, ti accetto subito la pull request!
